### ISSUE TITLE
SPM Version Support

### ISSUE THREAD

**Issue by xremix** [mobilinked/MbSwiftUIFirstResponder#3]
Hi @mobilinked ,

your library looks pretty promising to me, thanks or the work you did here! Having support for Swift Package Manager versions would be awesome, to easily integrate it into new projects and to make sure we can stick to a specific version in the future.

**Comment by mobilinked** [comment]
Hi @xremix, 

It's already a SPM, could you please try to import the package via https://github.com/Mobilinked/MbSwiftUIFirstResponder ?

**Comment by xremix** [comment]
@mobilinked thanks for your response - this works. I just updated my issue before you replied, that versioning would be great. New versions just would need a git tag.
