### ISSUE TITLE
SecureField and custom fields support.

### ISSUE THREAD

**Issue by unamed000** [mobilinked/MbSwiftUIFirstResponder#7]
I'm appreciate your work, but do we have a way to pass the firstResponder into SecureField or some other custom fields in case we need for it?

For now, i'm not able to use this package because it's missing support SecureField and some other stuff

**Comment by mobilinked** [comment]
This solution is to analyze the runtime view hierarchy and add additional control to the views SwiftUI created. It's hard to confirm if it's possible or impossible, and it's hard to know if the solution always works - as Apple may change the implementation, which may cause the logic to fail. This is a temp solution before Apple provides the official API. We are using it for our apps, and we try to make it flexible for the future to migrate to Apple's API. 

We will check if it's possible to support SecureField when we get time.
